services:
  - type: web
    name: futurepath-ai-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: futurepath-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: METALS_API_KEY
        sync: false
      - key: GOLD_API_KEY
        sync: false
      - key: METAL_PRICE_API_KEY
        sync: false

databases:
  - name: futurepath-db
    plan: free
    databaseName: futurepath
